### ISSUE TITLE
The Oomph setup is outdated

### ISSUE THREAD

**Issue by merks** [eclipse-sirius/sirius-desktop#179]
The setup definitely won't clone the right repository:

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/208716/b9b64127-44aa-4ae2-8afa-a0909e656a6b)

And the reference in the project catalog is this old location

https://git.eclipse.org/c/sirius/org.eclipse.sirius.git/plain/releng/org.eclipse.sirius.settings/Sirius.setup

rather than this new location:

https://raw.githubusercontent.com/eclipse-sirius/sirius-desktop/master/releng/org.eclipse.sirius.settings/Sirius.setup

I'll fix the latter as soon as Oomph's 1.31.0 release build completes.

**Comment by pcdavid** [comment]
I'm not sure anybody on the team actually uses Oomph (I don't), but if you have a fix I'll be happy to merge it.

**Comment by merks** [comment]
Your contribution guide is out of date too:

https://github.com/eclipse-sirius/sirius-desktop/blob/master/CONTRIBUTING

I guess there are not a lot of non-team contributors.  That might be a related to that not being so easy or of much interest to the team.

Maybe I have time to look or maybe I remove the link to it...

**Comment by merks** [comment]
It appears that the setup is many years outdated and I wonder if it ever worked.    I can't even activate the target platform manually:

![image](https://github.com/eclipse-sirius/sirius-desktop/assets/208716/4db6a1f5-bd39-4fb2-801b-de53474dc380)

Is there any documentation somewhere where describing what is needed to get to an error free workspace that I might try to automate?

**Comment by pcdavid** [comment]
It does not seem to be used by anyone on the team, I'll remove it to avoid confusion.

**Comment by ewillink** [comment]
> It does not seem to be used by anyone on the team, I'll remove it to avoid confusion
I sympathize with the sentiment since this was true for many of my projects too, but ...
For OCL, QVTd, QVTo I provided the OOMPH setups as a general Eclipse good citizen responsibility. For MoDisco, the merge and refactoring of EMF Facet and GMT made for an horrendous anarchy of stale plugins. I therefore use (and like) the MoDisco OOMPH setup for normal development.
OOMPH significantly reduces the usage barrier for non-developers. In principle an installation can be up and going quite quickly. Sadly the many Java/Platform/Orbit infrastructure changes mean that a 'latest' setup is likely to fail obscurely unless the setup has had regular TLC.
My recent burst of issues is driven by an attempt to develop the missing "Initialize Diagram" action so that a Sirius-based editor can work in a regular perspective just like the old Ecore Tools could. You provide no sources in SimRel so the traditional import plugins and fragments is broken. I have to workaround the missing OOMPH by using Ctrl-Shift-F2 to find an interesting Sirius plugin, check it out from GIT and then check out further plugins till the errors go away.
I urge you to reopen this bug, be a good Eclipse citizen, refresh the OOMPH setup and so support users who need to work with Sirius sources.
Once you have a viable OOMPH setup, even developers can find it useful to create a scratch installation to investigate a regression.
@merks Is it possible to use some setup actions to regularize a well-established traditional manual installation? (I would particularly like to refresh the WorkingSet assignments.)

**Comment by merks** [comment]
@ewillink 

You see the questions I asked above that seemed to have no answers.  I cannot support something that the team itself doesn't use, doesn't maintain, and apparently doesn't even want.  I think that's poor for the community, poor for attributing contributors, but that's not my choice to make.

**Comment by pcdavid** [comment]
> It appears that the setup is many years outdated and I wonder if it ever worked. I can't even activate the target platform manually:
> 
> ![image](https://private-user-images.githubusercontent.com/208716/286979410-4db6a1f5-bd39-4fb2-801b-de53474dc380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDM3MDQsIm5iZiI6MTcwMjY0MzQwNCwicGF0aCI6Ii8yMDg3MTYvMjg2OTc5NDEwLTRkYjZhMWY1LWJkMzktNGZiMi04MDFiLWRlNTM0NzRkYzM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMjMwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGZmMjE0NTk4NDkyNWQ0MTc5ZDI5OWY4OTA2MjA1MmZkM2Y1OGZhNmVhMzczM2JjZGU0NjI5ZTQ2NTU3Yjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JlJTCBniqv7y0jDaAattH9Gw6qyMOzC4gKIyrIeIe8c)
> 
> Is there any documentation somewhere where describing what is needed to get to an error free workspace that I might try to automate?

It used to work perfectly fine... until I switched to 2023-12. It still loads fine in 2023-09.
Just reported https://github.com/eclipse-pde/eclipse.pde/issues/1014.
