### ISSUE TITLE
Unsynchronized edges are recreated when a new edge with same mapping is created on the diagram

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#467]
Step to reproduce:
* Import the attached project [bugEdge.zip](https://github.com/user-attachments/files/17112662/bugEdge.zip)
* Open the diagram (there are 4 nodes and no edge)
* Create edge between cls1 and cls2
* **Expected**: a new edge is created between cls1 and cls2 but no others.
* **Actual**: a new edge is created between cls1 and cls2 (OK) but also between cls1 and cls3.

**Comment by scosta-obeo** [comment]
Step to validate:

1. Import the attached project [bugEdge.zip](https://github.com/user-attachments/files/17112662/bugEdge.zip)
2. Open the diagram (there are 4 nodes and no edge)
3. Create edge between cls1 and cls2
4. Expected: a new edge is created between cls1 and cls2 but no others.

**Comment by mPorhel** [comment]
Regression found in Sirius unit tests.
The provided fix does not handle the extra mapping cases (edge tool creation two border nodes + an edge for example)
The validation of the createDEdgeTask which automatically creates an edge from the EdgeCreationTool should check the semanticElement of the edgeCandidates rather than the correspondance of the clicked sourceView/targetView and the candidate sourceView/targetView.  

Such validation on source/target would be touchy : extra mappings, mappings imports, complex structure created by tools.
Draft fix already under tests.

Regression identified in 
*  HideRevealEdgeLabelsTest
* EdgeCreationPositionTest
* EdgeCreationPositionWithSnapToGridTest
* EdgeWithBorderNodeCreationPositionWithSnapToGridTest

**Comment by SteveMonnier** [comment]
[bugEdge_version_fixed.zip](https://github.com/user-attachments/files/18168437/bugEdge_version_fixed.zip)
Validated with OD 11.9.1 but I had to fix some version number in the .odesign and .representations files
